# Generated by Django 2.0.2 on 2020-04-05 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='hey',
            new_name='key',
        ),
    ]
